/*
 * This source file was generated by the Gradle 'init' task
 */
package net.its26;

import java.io.IOException;
import java.net.Socket;

public class Alice 
{
    private static final String BOBS_IP = "localhost";
    private static final int BOBS_PORT = 12345;

    public static void main(String[] args) 
    {
        try (Socket socket = new Socket(BOBS_IP, BOBS_PORT)) 
        {
            String helloMessage = "Hello, Bob.";
            System.out.println("Sending to Bob: " + helloMessage);
            MQV.sendMessage(helloMessage.getBytes(), socket.getOutputStream());
            String bobsReply = new String(MQV.receiveMessage(socket.getInputStream()));
            System.out.println("Bob replied: " + bobsReply);
        } 
        catch (IOException e) 
        {
            e.printStackTrace();
        }
    }
}
