/*
 * This source file was generated by the Gradle 'init' task
 */
package net.its26;

public class Server 
{

    public static void main(String[] args) 
    {
        System.out.println("Hello, I am the Server.");
    }
}