/*
 * This source file was generated by the Gradle 'init' task
 */
package net.its26;

import java.io.OutputStream;
import java.io.PrintWriter;
import java.net.Socket;

public class Client 
{
    public static void main(String[] args) 
    {
        String argsJoined = String.join(" ", args);
        sendMessage(argsJoined);
    }

    private static void sendMessage(String message)
    {

        final String SERVER_HOST = "localhost"; // Change to server's hostname or IP
        final int SERVER_PORT = 12345; // Port the server is listening on

        try (Socket socket = new Socket(SERVER_HOST, SERVER_PORT)) {
            System.out.println("Connected to the server.");

            // Get the output stream to send data
            OutputStream outputStream = socket.getOutputStream();
            PrintWriter writer = new PrintWriter(outputStream, true);

            // Send messages to the server
            writer.println(message);
        } 
        catch (Exception e) 
        {
            e.printStackTrace();
        }
    }
}